# fly.toml app configuration file
# Updated for dual-mode server

app = 'salesforce-mce-api'
primary_region = 'iad'

[build]

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '8080'
  MODE = 'http'  # IMPORTANT: Forces HTTP mode for Fly.io
  RATE_LIMIT_MAX_REQUESTS = '100'
  RATE_LIMIT_WINDOW_MS = '60000'
  REQUIRE_AUTH = 'false'  # Set to 'true' if you want auth

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'

[processes]
# Option 1: Use the HTTP-specific entry point (RECOMMENDED)
app = "node src/http-server.js"

# Option 2: Use the dual-mode file with MODE env var
# app = "node src/complete-server-implementation.js"